<h1>Статьи</h1>
<a href="/admin/article/add/">Добавить</a> <br><br>


<?php

$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div>'
        . '<button type="button" class="close" data-dismiss="alert" area-hidden="true">'
        . '&times'
        . '</button>'
        . '<ul><li>')->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

?>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Категория</th>
            <th>Заголовок</th>
            <th>Статья</th>
            <th>Начало статьи</th>
            <th>Опубликовано</th>
            <th>Действие</th>
        </tr> 
        
        <?php
        
            $i = 1;
            foreach ($articles as $item){
                
                $category = $item->getCategory();
                               
                /*if ($category) {
                   $catName = $category->getCategoryName();                    
                } 
                else{
                    $catName = ' ';
                }*/
                
                if ($item->getIsPublic()) {
                    $isPublic = 'Да';
                } 
                else {
                    $isPublic = 'Нет';
                }

                echo "<tr>"
                    . "<td>{$i}</td>"
                    . "<td>{$item->getCategory()}</td>"
                    . "<td>{$item->getTitle()}</td>"
                    . "<td>{$item->getArticleForTable()}</td>"
                    . "<td>{$item->getShortArticleForTable()}</td>"
                    . "<td>{$isPublic}</td>";
                                
                echo '<td><a href="'.$this->url('admin/article', array('action' => 'edit', 'id' => $item->getId()))
                      .'">Редактировать</a>&nbsp; &nbsp;
                      <a href="'.$this->url('admin/article', array('action' => 'delete', 'id' => $item->getId())) 
                      .'">Удалить статью</a>
                      </td></tr>';
                
                $i++;
            }
        
        ?>
   </tbody>
</table>

<?php

echo $this->paginationControl($articles, 'Sliding', 'pagination_control', array('route' => 'admin/article'));

?>
            
