<h1>Категории</h1>

<a href="/admin/category/add/">Добавить</a> <br><br>

<?php

$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div>'
        . '<button type="button" class="close" data-dismiss="alert" area-hidden="true">'
        . '&times'
        . '</button>'
        . '<ul><li>')->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

?>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Ключ</th>
            <th>Название</th>
            <th>Действие</th>
        </tr> 
        
        <?php
            $i = 1;
            foreach ($category as $item){
                echo "<tr>"
                . "<td>{$i}</td>"
                . "<td>{$item->getCategoryKey()}</td>"
                . "<td>{$item->getCategoryName()}</td>";
                
                echo '<td><a href="'.$this->url('admin/category', array('action' => 'edit', 'id' => $item->getId()))
                      .'">Редактировать</a>&nbsp; &nbsp;
                      <a href="'.$this->url('admin/category', array('action' => 'delete', 'id' => $item->getId())) 
                      .'">Удалить запись</a>
                      </td></tr>';
                $i++;     
            }
        ?>
        
    </tbody>
</table>
